<?php
/**
 * @file
 * An example field using the Field Types API.
 */

/**
 * @defgroup media_manager_core Example: Field Types API
 * @ingroup examples
 * @{
 * Examples using Field Types API.
 *
 * This is updated from Barry Jaspan's presentation at Drupalcon Paris,
 * @link http://acquia.com/community/resources/acquia-tv/intro-field-api-module-developers Video Presentation @endlink
 *
 * Providing a field requires:
 * - Defining a field:
 *   - hook_field_info()
 *   - hook_field_schema()
 *   - hook_field_validate()
 *   - hook_field_is_empty()
 *
 * - Defining a formatter for the field (the portion that outputs the field for
 *   display):
 *   - hook_field_formatter_info()
 *   - hook_field_formatter_view()
 *
 * - Defining a widget for the edit form:
 *   - hook_field_widget_info()
 *   - hook_field_widget_form()
 *
 * Our module defines the field in media_manager_core_field_info(),
 * media_manager_core_field_validate() and media_manager_core_field_is_empty().
 * media_manager_core_field_schema() is implemented in media_manager_core.install.
 *
 * Our module sets up a formatter in media_manager_core_field_formatter_info() and
 * media_manager_core_field_formatter_view(). These are the API hooks that present
 * formatted and themed output to the user.
 *
 * And finally, our module defines the widet in
 * media_manager_core_field_widget_info() and media_manager_core_field_widget_form().
 * The widget is the form element used to receive input from the user
 * when the field is being populated.
 *
 * @see field_types
 * @see field
 */

/***************************************************************
 * Field Type API hooks
 ***************************************************************/

/**
 * Implements hook_field_info().
 *
 * Provides the description of the field.
 */
function media_manager_core_field_info() {
  return array(
    // We name our field as the associative name of the array.
    'media_manager_core' => array(
      'label' => t('Media Manager'),
      'description' => t('Demonstrates a field composed of an RGB color.'),
      'default_widget' => 'media_manager_core_3text',
      'default_formatter' => 'media_manager_core_simple_text',
    ),
  );
}

/**
 * Implements hook_field_validate().
 *
 * This hook gives us a chance to validate content that's in our
 * field. We're really only interested in the $items parameter, since
 * it holds arrays representing content in the field we've defined.
 * We want to verify that the items only contain RGB hex values like
 * this: #RRGGBB. If the item validates, we do nothing. If it doesn't
 * validate, we add our own error notification to the $errors parameter.
 *
 * @see media_manager_core_field_widget_error()
 */
function media_manager_core_field_validate($entity_type, $entity, $field, $instance, $langcode, $items, &$errors) {

}


/**
 * Implements hook_field_is_empty().
 *
 * hook_field_is_emtpy() is where Drupal asks us if this field is empty.
 * Return TRUE if it does not contain data, FALSE if it does. This lets
 * the form API flag an error when required fields are empty.
 */
function media_manager_core_field_is_empty($item, $field) {
  return empty($item['media_manager']);
}

/**
 * Implements hook_field_formatter_info().
 *
 * We need to tell Drupal that we have two different types of formatters
 * for this field. One will change the text color, and the other will
 * change the background color.
 *
 * @see media_manager_core_field_formatter_view()
 */
function media_manager_core_field_formatter_info() {
  return array(
    // This formatter just displays the hex value in the color indicated.
    'media_manager_core_simple_text' => array(
      'label' => t('Simple text-based formatter'),
      'field types' => array('media_manager_core'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 *
 * Two formatters are implemented.
 * - media_manager_core_simple_text just outputs markup indicating the color that
 *   was entered and uses an inline style to set the text color to that value.
 * - media_manager_core_color_background does the same but also changes the
 *   background color of div.region-content.
 *
 * @see media_manager_core_field_formatter_info()
 */
function media_manager_core_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  
  switch ($display['type']) {
    // This formatter simply outputs the field as text and with a color.
    case 'media_manager_core_simple_text':
      foreach ($items as $delta => $item) {
        drupal_add_js(drupal_get_path('module', 'media_manager_core') .'/js/script.js', 'file');
        $theme = array('data' => $item['media_manager']);
        $element[$delta] = array(
          // We create a render array to produce the desired markup,
          // "<p style="color: #hexcolor">The color code ... #hexcolor</p>".
          // See theme_html_tag().
          '#type' => 'html_tag',
          '#tag' => 'div',
          '#attributes' => array(
            'style' => 'color: blue',
            'class' => array('media-manager-video', 'video'),
          ),
          '#value' => theme('player',$theme),
        );
      }
      break;

    // This formatter adds css to the page changing the '.region-content' area's
    // background color. If there are many fields, the last one will win.
  }

  return $element;
}

/**
 * Implements hook_field_widget_info().
 *
 * Three widgets are provided.
 * - A simple text-only widget where the user enters the '#ffffff'.
 * - A 3-textfield widget that gathers the red, green, and blue values
 *   separately.
 * - A farbtastic colorpicker widget that chooses the value graphically.
 *
 * These widget types will eventually show up in hook_field_widget_form,
 * where we will have to flesh them out.
 *
 * @see media_manager_core_field_widget_form()
 */
function media_manager_core_field_widget_info() {
  return array(
    'media_manager_core_text' => array(
      'label' => t('Video ID'),
      'field types' => array('media_manager_core'),
    ),
  );
}

/**
 * Implements hook_field_widget_form().
 *
 * hook_widget_form() is where Drupal tells us to create form elements for
 * our field's widget.
 *
 * We provide one of three different forms, depending on the widget type of
 * the Form API item provided.
 *
 * The 'media_manager_core_colorpicker' and 'media_manager_core_text' are essentially
 * the same, but media_manager_core_colorpicker adds a javascript colorpicker
 * helper.
 *
 * media_manager_core_3text displays three text fields, one each for red, green,
 * and blue. However, the field type defines a single text column,
 * rgb, which needs an HTML color spec. Define an element validate
 * handler that converts our r, g, and b fields into a simulated single
 * 'rgb' form element.
 */
function media_manager_core_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  $value = isset($items[$delta]['media_manager']) ? $items[$delta]['media_manager'] : '';

  $widget = $element;
  $widget['#delta'] = $delta;

  switch ($instance['widget']['type']) {

    case 'media_manager_core_text':
      $widget += array(
        '#type' => 'textfield',
        '#default_value' => $value,
        // Allow a slightly larger size that the field length to allow for some
        // configurations where all characters won't fit in input field.
        '#size' => 20,
        '#maxlength' => 30,
      );
      break;

   }

  $element['media_manager'] = $widget;
  return $element;
}

/**
 * Implements hook_field_widget_error().
 *
 * hook_field_widget_error() lets us figure out what to do with errors
 * we might have generated in hook_field_validate(). Generally, we'll just
 * call form_error().
 *
 * @see media_manager_core_field_validate()
 * @see form_error()
 */
function media_manager_core_field_widget_error($element, $error, $form, &$form_state) {
  switch ($error['error']) {
    case 'media_manager_core_invalid':
      form_error($element, $error['message']);
      break;
  }
}


/**
 * Implements hook_menu().
 *
 * Provides a simple user interface that tells the developer where to go.
 */
function media_manager_core_menu() {
  $items['examples/media_manager_core'] = array(
    'title' => 'Field Example',
    'page callback' => '_media_manager_core_page',
    'access callback' => TRUE,
  );
  return $items;
}

/**
 * A simple page to explain to the developer what to do.
 */
function _media_manager_core_page() {
  return t("The Field Example provides a field composed of an HTML RGB value, like #ff00ff. To use it, add the field to a content type.");
}

function media_manager_core_theme() {
  return array(
    'player' => array(
      'template' => 'templates/player',
      'variables' => array('data' => ''),
    ),
  );
}

/**
 * @} End of "defgroup media_manager_core".
 */